// Design System: Vivid Editorial Minimalism

export const designTokens = {
  colors: {
    surface: '#fcf9f8',
    'surface-dim': '#dcd9d9',
    'surface-bright': '#fcf9f8',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#f6f3f2',
    'surface-container': '#f0eded',
    'surface-container-high': '#eae7e7',
    'surface-container-highest': '#e5e2e1',
    'on-surface': '#1c1b1b',
    'on-surface-variant': '#464652',
    'inverse-surface': '#313030',
    'inverse-on-surface': '#f3f0ef',
    outline: '#777683',
    'outline-variant': '#c7c5d4',
    'surface-tint': '#4f54b4',
    primary: '#15157d',
    'on-primary': '#ffffff',
    'primary-container': '#2e3192',
    'on-primary-container': '#9da1ff',
    'inverse-primary': '#c0c1ff',
    secondary: '#ad3300',
    'on-secondary': '#ffffff',
    'secondary-container': '#ff642d',
    'on-secondary-container': '#5a1600',
    tertiary: '#4f1502',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#6c2a14',
    'on-tertiary-container': '#f09174',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#93000a',
    'primary-fixed': '#e1e0ff',
    'primary-fixed-dim': '#c0c1ff',
    'on-primary-fixed': '#04006d',
    'on-primary-fixed-variant': '#373a9b',
    'secondary-fixed': '#ffdbd0',
    'secondary-fixed-dim': '#ffb59e',
    'on-secondary-fixed': '#3a0b00',
    'on-secondary-fixed-variant': '#842500',
    'tertiary-fixed': '#ffdbd0',
    'tertiary-fixed-dim': '#ffb59e',
    'on-tertiary-fixed': '#3a0b00',
    'on-tertiary-fixed-variant': '#76321c',
    background: '#fcf9f8',
    'on-background': '#1c1b1b',
    'surface-variant': '#e5e2e1',
  },
  typography: {
    'display-lg': {
      fontFamily: 'Young Serif',
      fontSize: '48px',
      fontWeight: 400,
      lineHeight: '56px',
      letterSpacing: '-0.02em',
    },
    'headline-lg': {
      fontFamily: 'Young Serif',
      fontSize: '32px',
      fontWeight: 400,
      lineHeight: '40px',
    },
    'headline-lg-mobile': {
      fontFamily: 'Young Serif',
      fontSize: '28px',
      fontWeight: 400,
      lineHeight: '34px',
    },
    'headline-md': {
      fontFamily: 'Young Serif',
      fontSize: '24px',
      fontWeight: 400,
      lineHeight: '32px',
    },
    'body-lg': {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: '18px',
      fontWeight: 400,
      lineHeight: '28px',
    },
    'body-md': {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: '16px',
      fontWeight: 400,
      lineHeight: '24px',
    },
    'label-md': {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: '14px',
      fontWeight: 600,
      lineHeight: '20px',
      letterSpacing: '0.05em',
    },
    'label-sm': {
      fontFamily: 'Plus Jakarta Sans',
      fontSize: '12px',
      fontWeight: 700,
      lineHeight: '16px',
      letterSpacing: '0.08em',
    },
  },
  rounded: {
    sm: '0.25rem',
    DEFAULT: '0.5rem',
    md: '0.75rem',
    lg: '1rem',
    xl: '1.5rem',
    full: '9999px',
  },
  spacing: {
    unit: '8px',
    'container-margin-mobile': '20px',
    'container-margin-desktop': '64px',
    gutter: '16px',
    'section-gap': '48px',
  },
  gradients: {
    primary: 'linear-gradient(135deg, #15157d 0%, #ad3300 100%)',
    'primary-alt': 'linear-gradient(90deg, #ad3300 0%, #15157d 100%)',
  },
};

export type DesignTokens = typeof designTokens;
